title: MFI Gamepad Feeder
name: MFI Gamepad Feeder
description: Use your MFI (Made for iPhone/iPad) Gamepad on Windows!
google_analytics: UA-231768-10
show_downloads: true
theme: jekyll-theme-architect
gems:
  - jekyll-mentions
